### PR TITLE
Wave/ERC721

### PR DESCRIPTION
**Pull request by 0x3at**
v0 Code for ERC 721
essential git attributes for solidity readability within the repo
Approved NFT source images and config files

### CODE REVIEW

**Comment by 0x3at** [comment]
reopening as I forgot to add reviewers

**Comment by 0x3at** [comment]
requesting PR approval on ERC721 v0 as well as Mutlisigv0 

Established .src files for solidity and .gitattributes

**Review by TheHumanistX — COMMENTED** [review]
Approve

**Review by TheHumanistX — APPROVED** [review]

**Review by lyfewyse — APPROVED** [review]
Approved

**Review by farfromthetree — APPROVED** [review]

**Pull request merged**
